name: DogMiner
version: ${project.version}
author: eliottness
main: com.softalys.DogMinerPlugin
commands:
    dogminer:
        description: DogMiner build information command.
        usage: /<command>
    lag:
        description: Submits a lag report.
        usage: /<command>
